---
title: "Clustering Based on Zonal Statistics"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, warning=FALSE, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(factoextra)
library(readr)
library(clustertend)
library(psych)
library(fpc)
library(dbscan)
library(gridExtra)
library(seriation)
library(dendextend)
```

``` {r make matrix}
# Read CSV
roof_matrix <- read_csv(file.choose())
head(roof_matrix)
# Rename first column if necesary
if (colnames(roof_matrix)[1] != "roof") {
roof_matrix <- roof_matrix %>% rename(roof = X1)
}
roof_matrix <- roof_matrix[complete.cases(roof_matrix), ]
```

```{r kmeans, message=FALSE, warning=FALSE}
run_kmeans <- function(roof_matrix, clusters, filename) {
  ###This function runs the entire k-means algorithm ###
  
  # Scale and find covariance matrix
  roof_scaled <- roof_matrix %>% select(-roof) %>%
                                 scale()
  dist_can <- roof_scaled %>% dist(method="canberra")
  # Plot ODI
  title1 <- paste("ODI:", filename, sep=" ")
  viz <- fviz_dist(dist_can,
                   show_labels = FALSE,
                   gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07")) +
                   ggtitle(title1)
  plot(viz)
  
  # K-means
  k2 <- kmeans(roof_scaled, centers=clusters, nstart = 15)
  output <- roof_matrix %>% select(roof)
  output$K_Cluster <- as.factor(k2$cluster)
  k_title <- paste("K = ", clusters, sep="")
  title2 <- paste(k_title, filename, sep=" ")
  group <- fviz_cluster(k2, geom = "point", data = roof_scaled) +
           ggtitle(title2)
  plot(group)
  
  # Comparison to actual labels
  grouped <- aggregate(output,
                       by=list(output$roof, output$K_Cluster),
                       FUN=length)
  colnames(grouped)[colnames(grouped)=="Group.2"] <- "Cluster"
  actual_label_count <-table(roof_matrix$roof)
  title3 <- paste("Comparison to actual labels:", filename, sep=" ")
  bar <- ggplot(grouped, aes(fill=Cluster, y=K_Cluster, x=Group.1)) + 
                geom_bar(position="dodge", stat="identity") +
                xlab("Roof Material") +
                ylab("Count") +
                ggtitle(title3)
  plot(bar)
  
  bar1 <- ggplot(grouped, aes(fill=Group.1, y=K_Cluster, x=Cluster)) + 
    geom_bar(position="dodge", stat="identity") +
    xlab("Cluster") +
    ylab("Count") +
    ggtitle("Group by Cluster")
  
  plot(bar1)
}
```

```{r warning=FALSE, message=FALSE}
run_hac <- function(roof_matrix, clusters, distance, method, file) {
  ###This function runs the entire factor analysis algorithm ###

  # Scale
  roof_scaled <- roof_matrix %>% select(-roof) %>%
                                 scale() %>%
                                 dist(method=distance)
  hc_complete <- hclust(roof_scaled, method=method)
  title5 <- paste("HAC:", file, sep=" ")
  plot(hc_complete %>%
       as.dendrogram %>%
       set("branches_k_color", k=clusters),
       leaflab="none",
       main = title5)
  
  # Cut the tree at k=5
  cut <- cutree(hc_complete, k=clusters)
  output <- roof_matrix %>% select(roof)
  output$K_Cluster <- as.factor(cut)
  grouped <- aggregate(output,
                       by=list(output$roof, output$K_Cluster),
                       FUN=length)
  colnames(grouped)[colnames(grouped)=="Group.2"] <- "Cluster"
  actual_label_count <-table(roof_matrix$roof)
  title3 <- paste("HAC Comparison to Actual Labels:", file, sep=" ")
  bar <- ggplot(grouped, aes(fill=Cluster, y=K_Cluster, x=Group.1)) + 
                geom_bar(position="dodge", stat="identity") +
                xlab("Roof Material") +
                ylab("Count") +
                ggtitle(title3)
  plot(bar)
  
  # Plot the inverse
  bar1 <- ggplot(grouped, aes(fill=Group.1, y=K_Cluster, x=Cluster)) + 
  geom_bar(position="dodge", stat="identity") +
  xlab("Cluster") +
  ylab("Count") +
  ggtitle("Group by Cluster")
  
  plot(bar1)
}
```

```{r k-medoids, message=FALSE, warning=FALSE}
run_PAM <- function(roof_matrix, clusters, name) {
  ## This function runs the entire PAM algorithm ##
  roof_scaled <- roof_matrix %>% 
    select(-roof) %>%
    scale()
  
  PAM <- pam(roof_scaled,
           k=clusters)
  output <- roof_matrix %>% select(roof)
  output$pamCluster <- as.factor(PAM$cluster)
  grouped <- aggregate(output,
                     by=list(output$roof, output$pamCluster),
                     FUN=length)
  
  ggplot(grouped2, aes(fill=Group.1, y=pamCluster, x=Group.2)) + 
    geom_bar(position="dodge", stat="identity") +
    xlab("Roof Material") +
    ylab("Count") +
    ggtitle("title3")
  }
```

```{r DBSCAN, message=FALSE, warning=FALSE}
run_DBSCAN <- function(roof, eps, minpts, file) {
  d <- dbscan(roof, eps=eps, Minpts=minpts)
  print(d)
}
```

```{r}
# First define eps
roof <- roof_matrix %>% select(-roof) %>%
                        scale()
# Determine best eps
kNNdistplot(roof, k=3)
# Note: MinPts = k above
run_DBSCAN(roof, eps=55, MinPts=100, "mixco_1_and_ebenezer_gcf")
```

```{r results, message=FALSE, warning=FALSE}
run_kmeans(roof_matrix, 2, "guatemala_full_100")
run_kmeans(roof_matrix, 2, "mixco_1_and_ebenezer_gcf")
run_kmeans(roof_matrix, 4, "zonal_test")
run_hac(roof_matrix, 4, distance="canberra", method="complete", file="mixco_1_and_ebenezer_full")
```

